# Use NumPy to simulate daily prayer attendance in a mosque for 30 days. Reshape into 6×5, then extract 2nd row, 4th column, and a 3×3 sub-matrix.

In [16]:
import pandas as pd
import numpy as np

In [26]:
attendance = np.random.randint(50, 500,(30))

In [29]:
arrangement = attendance.reshape(6,5)
arrangement

array([[374, 448, 470, 106, 272],
       [404, 209, 337, 378, 262],
       [405,  86, 490, 294, 361],
       [281, 461, 292, 496, 176],
       [372, 184, 298, 228, 345],
       [246, 314, 321, 351, 134]], dtype=int32)

In [38]:
arrangement[1] #subsetting

array([404, 209, 337, 378, 262], dtype=int32)

In [41]:
arrangement[0:5,3] #slicing

array([106, 378, 294, 496, 228], dtype=int32)

In [47]:
arrangement[[0,1,2]][:,[0,1,2]] #fancy i

array([[374, 448, 470],
       [404, 209, 337],
       [405,  86, 490]], dtype=int32)